version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - ENDPOINT=http://0.0.0.0:9000/api
      - HOST=0.0.0.0
  backend:
    build: ./backend
    ports:
      - 9000:9000
    environment:
      - PORT=9000
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Helsinki,fi
      - APPID=